######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 11 00:07:29 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/r/u/ruship/EC535/ruship_Lab5/QT/. .

# Input
HEADERS += update.h
SOURCES += main.cpp update.cpp
